
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: person-service-quarkus
  description: |
    The Person Service for managing person-related data
    
    [![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Aperson-service-quarkus&metric=alert_status)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Aperson-service-quarkus)
    [![Coverage](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Aperson-service-quarkus&metric=coverage)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Aperson-service-quarkus)

    [![Security Rating](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Aperson-service-quarkus&metric=security_rating)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Aperson-service-quarkus)
    [![Reliability Rating](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Aperson-service-quarkus&metric=reliability_rating)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Aperson-service-quarkus)
    [![Maintainability Rating](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Aperson-service-quarkus&metric=sqale_rating)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Aperson-service-quarkus)
  tags:
    - spring-boot
    - microservice
  annotations:
    github.com/project-slug: goafabric/person-service-quarkus
    backstage.io/techdocs-ref: dir:./doc/techdocs
    backstage.io/adr-location: https://github.com/goafabric/backstage/tree/develop/catalog/adr/person-service
    #backstage.io/techdocs-ref: url:https://github.com/goafabric/backstage/tree/techdos/catalog/techdocs/person-service-quarkus
  links:
    - url: https://github.com/goafabric/person-service-quarkus
      title: GitHub Repository
spec:
  type: service
  lifecycle: production
  owner: team-green
  
  providesApis:
    - person-api
  dependsOn:
    - component:callee-service

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: person-api
  description: OpenAPI definition for Core Service.
  tags:
    - openapi
    - person-service-quarkus-service
spec:
  type: openapi
  lifecycle: production
  owner: team-blue
  definition:
    $text: doc/generated/openapi.json

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: person-topic
  description: Person Example Topic
  tags:
    - kafka-topic
    - person-service-quarkus
spec:
  type: kafka-topic
  lifecycle: production
  owner: devops
  definition: |
    topic: person
    type:  person
    key: person_id
    EventData.operation: CREATE | UPDATE | DELETE