#web
quarkus.application.name=person-service
quarkus.http.port=50800
quarkus.http.io-threads=20

#monitoring
quarkus.smallrye-health.root-path=/actuator/health
quarkus.smallrye-health.liveness-path=/actuator/health/liveness
quarkus.smallrye-health.readiness-path=/actuator/health/readiness
quarkus.micrometer.export.prometheus.path=/actuator/prometheus

#openapi
quarkus.swagger-ui.always-include=false
quarkus.smallrye-openapi.store-schema-directory=doc/generated

#tracing
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
quarkus.datasource.jdbc.telemetry=false
quarkus.log.category."io.opentelemetry.exporter.internal".level=OFF
quarkus.log.category."io.quarkus.opentelemetry.runtime.exporter.otlp.sender".level=OFF

#persistence
%dev.quarkus.datasource.db-kind = h2
%dev.quarkus.datasource.jdbc.url = jdbc:h2:mem:person;DATABASE_TO_UPPER=FALSE

%test.quarkus.datasource.db-kind = h2
%test.quarkus.datasource.jdbc.url = jdbc:h2:mem:persondb

%prod.quarkus.datasource.db-kind = postgresql

quarkus.datasource.jdbc.max-size=10
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.validate-in-dev-mode=false
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

#multi Tenancy
quarkus.hibernate-orm.multitenant=SCHEMA
quarkus.flyway.migrate-at-start=false

multi-tenancy.tenants=0,5
multi-tenancy.schema-prefix=person_
database.provisioning.goals="-migrate -import-demo-data"

#adapter
adapter.timeout=10000
adapter.failureRate=0.5
adapter.openDuration=30000
adapter.circuitBreaker.enabled=true

adapter.calleeservice.url=http://localhost:50900

org.goafabric.personservice.adapter.CalleeServiceAdapter/mp-rest/url=${adapter.calleeservice.url}
org.goafabric.personservice.adapter.CalleeServiceAdapter/mp-rest/connectTimeout=${adapter.timeout}
org.goafabric.personservice.adapter.CalleeServiceAdapter/mp-rest/readTimeout=${adapter.timeout}

#https://quarkus.io/guides/smallrye-fault-tolerance#adding-resiliency-circuit-breaker
Timeout=${adapter.timeout}
CircuitBreaker/requestVolumeThreshold=10
CircuitBreaker/failureRatio=${adapter.failureRate}
CircuitBreaker/delay=${adapter.openDuration}
CircuitBreaker/enabled=${adapter.circuitBreaker.enabled}

#kafka
mp.messaging.outgoing.general.enabled=false
mp.messaging.outgoing.general.connector=smallrye-kafka
#%dev.kafka.bootstrap.servers=localhost:9092

#blob
quarkus.azure.storage.blob.enabled=false
azure.storage.blob.container-name=person
#%dev.quarkus.azure.storage.blob.connection-string=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1
#%dev.quarkus.azure.storage.blob.connection-string=DefaultEndpointsProtocol=https;AccountName=${azure.storage.blob.account-name};AccountKey=${azure.storage.blob.account-key};EndpointSuffix=core.windows.net

#mcp
quarkus.mcp.server.server-info.instructions="You are a Person Assistant that can return Persons based on multiple methods"

#logging
quarkus.log.console.format=%d{HH:mm:ss} %-5p tenantId=%X{tenantId} [%X{traceId}] [%c{2.}] (%t) %s%e%n

quarkus.log.level=INFO
quarkus.log.category."org.goafabric".level=INFO
quarkus.log.category."org.flywaydb.core".level=INFO
quarkus.log.category."org.hibernate".level=INFO

#jacoco
quarkus.jacoco.report=false

